"""sync_models_with_db

Revision ID: e00a872a6c64
Revises: 71511212b493
Create Date: 2026-01-02 01:50:10.161305

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e00a872a6c64'
down_revision = '71511212b493'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_balance', sa.Numeric(10, 2), server_default='0.00', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    # ### end Alembic commands ###
